### ISSUE TITLE
大佬真的太强了！非常感谢！

### ISSUE THREAD

**Issue by Suxmx** [EasyVulkan/EasyVulkan.github.io#6]
从来没有读过如此详尽易懂的教程，感觉简直是在观赏一个艺术品！这个教程对我的帮助真的很大，感激不尽！

**Comment by EasyVulkan** [comment]
你是第一个说好懂的。。。/半哭半笑emoji

谢谢反馈。
我觉得自己把握不好尺度，有些部分写得像是把读者当猴子，还有些长篇大论是在讲解释程序设计而非Vulkan本身。
希望你读到后面还觉得好懂。。。

**Comment by Suxmx** [comment]
我应该算是看到比较后面了hhh虽然有些地方确实很难啃，但是大多是因为vulkan本身的复杂性吧。感觉大佬已经讲的非常详细了！

**Comment by Suxmx** [comment]
好的！真的很感谢大佬，虽然本来只是在google上随便搜了下，但是这几周边看边啃已经差不多能搓出一个渲染器自己写点shader了，对学图形的学生来说帮助真的很大。不继续打扰大佬了hhhh
